import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

const read = (path) => fs.readFileSync(path, "utf8");
const settingsSource = read("src/components/global/GlobalSettings.vue");
const storeSource = read("src/stores/mcpActivity.js");
const activityPanelSource = read("src/components/global/McpActivityPanel.vue");
const settingsPanelSource = read("src/components/global/McpSettingsPanel.vue");
const activityPageSource = read("src/pages/McpActivityPage.vue");
const mainLayoutSource = read("src/layouts/MainLayout.vue");
const preloadSource = read("src-electron/electron-preload.js");
const routesSource = read("src/router/routes.js");
const toolbarSource = read("src/components/global/MainToolbar.vue");
const electronMcpApiSource = read("src/utils/electronMcpApi.js");

test("MCP UI keeps activity logs in a sibling tab inside global settings", () => {
  assert.match(settingsSource, /q-tab name="mcp"/);
  assert.match(settingsSource, /McpSettingsPanel/);
  assert.match(settingsSource, /validTabs = \[[^\]]*"mcp"/);
  assert.match(routesSource, /path: "activity\/mcp"/);
  assert.match(routesSource, /pages\/McpActivityPage\.vue/);
  assert.match(settingsPanelSource, /<McpActivityPanel \/>/);
  assert.match(settingsPanelSource, /<q-tab name="activity"/);
  assert.match(settingsPanelSource, /activeSection/);
  assert.match(settingsSource, /:initial-tab="initialMcpTab"/);
  assert.doesNotMatch(settingsSource, /showMcpActivityDialog|mcp-activity-dialog|McpActivityPanel/);
  assert.match(mainLayoutSource, /onTrayNavigation/);
  assert.match(mainLayoutSource, /request\?\.route !== "\/activity\/mcp"/);
  assert.match(mainLayoutSource, /showBackendManager\.value = false/);
  assert.match(mainLayoutSource, /openGlobalSettings\(\{ tab: "mcp", mcpTab: "activity" \}\)/);
  assert.doesNotMatch(mainLayoutSource, /router\.push\(request\.route\)/);
  assert.match(mainLayoutSource, /removeTrayNavigationListener\?\.\(\)/);
  assert.match(mainLayoutSource, /send\?\.\("renderer-ready"\)/);
  assert.doesNotMatch(activityPanelSource, /onMounted/);
  assert.match(activityPageSource, /onMounted/);
  assert.match(activityPageSource, /void store\.refresh\(\)/);
  assert.match(mainLayoutSource, /runtimeOnboardingDismissed\.value = true/);
  assert.doesNotMatch(toolbarSource, /nav-mcp|MCP 活动/);
});

test("MCP renderer store uses named preload wrappers and bounded projections", () => {
  assert.match(storeSource, /getMcpState/);
  assert.match(storeSource, /getMcpActivity\(0\)/);
  assert.doesNotMatch(storeSource, /startMcp|stopMcp/);
  assert.match(storeSource, /REQUEST_ID_PATTERN/);
  assert.match(storeSource, /TOOL_NAMES\.has/);
  assert.match(storeSource, /MCP_ALLOWED_TOOL_OPTIONS/);
  assert.match(storeSource, /new Set\(MCP_ALLOWED_TOOL_OPTIONS\)/);
  assert.match(storeSource, /OUTCOMES\.has/);
  assert.match(storeSource, /CONFIRMATION_LIMIT_REACHED/);
  assert.match(storeSource, /CONFIRMATION_REQUIRED/);
  assert.match(storeSource, /INVALID_JOB_ID/);
  assert.match(storeSource, /PATH_NOT_ALLOWED/);
  assert.match(storeSource, /TOOL_NOT_ALLOWED/);
  assert.match(storeSource, /getMcpClientConfiguration/);
  assert.match(storeSource, /getMcpClientSessions/);
  assert.match(storeSource, /getMcpApprovals/);
  assert.match(storeSource, /disconnectMcpClient/);
  assert.match(storeSource, /resolveMcpApproval/);
  assert.match(storeSource, /openMcpArtifactInEditor/);
  assert.match(storeSource, /safeArtifact/);
  assert.match(storeSource, /safeFileResult/);
  assert.match(storeSource, /SAFE_ID_PATTERN/);
  assert.doesNotMatch(storeSource, /cause\?\.message/);
  assert.doesNotMatch(storeSource, /ipcRenderer|invoke\(/);
  assert.match(activityPanelSource, /mcp-activity-panel/);
  assert.match(settingsPanelSource, /openActivity/);
});

test("MCP settings explains and presents the policy controls consistently", () => {
  assert.match(settingsPanelSource, /只允许所选工具被外部 MCP 客户端调用/);
  assert.match(settingsPanelSource, /选择工具白名单/);
  assert.match(settingsPanelSource, /scope\.opt\.description/);
  assert.match(settingsPanelSource, /confirmationMode/);
  assert.match(settingsPanelSource, /只读/);
  assert.match(settingsPanelSource, /自动审批/);
  assert.match(settingsPanelSource, /完全访问权限/);
  assert.match(settingsPanelSource, /启用 MCP 前至少选择一个允许目录/);
  assert.match(settingsPanelSource, /MCP_ALLOWED_ROOT_REQUIRED/);
  assert.match(settingsPanelSource, /MCP_ALLOWED_TOOL_REQUIRED/);
  assert.match(settingsPanelSource, /await store\.refresh\(\)/);
  assert.match(settingsPanelSource, /选择信任的目录/);
  assert.match(settingsPanelSource, /aria-label="选择信任的目录"/);
  assert.doesNotMatch(settingsPanelSource, /服务开关/);
  assert.match(settingsPanelSource, /label="启动"/);
  assert.match(settingsPanelSource, /label="停止"/);
  assert.match(settingsPanelSource, /mcp-lifecycle-button/);
  assert.match(settingsPanelSource, /工具权限/);
  assert.match(settingsPanelSource, /目录权限/);
  assert.match(settingsPanelSource, /确认策略/);
  assert.match(settingsPanelSource, /MCP 服务设置仅在 Electron 应用中可用/);
 assert.match(settingsPanelSource, /MCP 主进程桥接不可用/);
  assert.match(settingsPanelSource, /electronCapabilityMessage/);
 assert.match(settingsPanelSource, /getElectronMcpCapability/);
  assert.match(storeSource, /getElectronMcpCapability\(\)\.api/);
  assert.match(electronMcpApiSource, /electronBridge\.ipcRenderer/);
  assert.match(electronMcpApiSource, /MCP_API_METHODS\.every/);
  assert.match(electronMcpApiSource, /MCP_EXTERNAL_API_METHODS/);
  assert.doesNotMatch(settingsSource, /mcp-activity-dialog|showMcpActivityDialog/);
  assert.match(settingsPanelSource, /mcp-capability-banner/);
  assert.match(settingsPanelSource, /MCP 策略会自动保存，不受全局保存或取消影响。/);
  assert.doesNotMatch(settingsPanelSource, /label="保存 MCP 策略"/);
  assert.match(settingsPanelSource, /scope\.toggleOption\(scope\.opt\)/);
  assert.match(settingsPanelSource, /@click\.stop="scope\.toggleOption\(scope\.opt\)"/);
  assert.doesNotMatch(settingsPanelSource, /@update:model-value="scope\.toggleOption\(scope\.opt\)"/);
  assert.match(settingsPanelSource, /watch\(mcpConfig, scheduleMcpAutosave, \{ deep: true \}\)/);
  assert.match(settingsPanelSource, /snapshot\.enabled === true && mcpConfig\.value\.enabled === true/);
  assert.match(settingsPanelSource, /let mcpSaveEpoch = 0/);
  assert.match(settingsPanelSource, /saveEpoch !== mcpSaveEpoch && snapshot\.enabled === true/);
  assert.match(settingsPanelSource, /mcpSaveEpoch \+= 1/);
  assert.match(settingsPanelSource, /rollbackMcpAfterSaveFailure/);
  assert.match(settingsPanelSource, /failureCode === "MCP_ROOT_INVALID" \? \[\] : mcpConfig\.value\.allowedRoots/);
  assert.match(settingsPanelSource, /MCP 已自动关闭，请修正策略后手动重新启用/);
  assert.match(settingsPanelSource, /void enqueueMcpSave\(policyPayload\(\)\)\.finally/);
  assert.match(settingsPanelSource, /已取消选择允许目录/);
  assert.match(settingsPanelSource, /mcp-module-grid/);
  assert.match(settingsPanelSource, /grid-template-areas/);
  assert.match(settingsPanelSource, /copyClientConfiguration/);
  assert.match(settingsPanelSource, /label="复制 AI 提示词"/);
  assert.match(settingsPanelSource, /clientAiPrompt/);
  assert.match(settingsPanelSource, /copyClientAiPrompt/);
  assert.match(settingsPanelSource, /moonshine\.status/);
  assert.match(settingsPanelSource, /moonshine\.capabilities/);
  assert.match(settingsPanelSource, /probeExternalProxy/);
  assert.match(settingsPanelSource, /disconnectClientSession/);
  assert.match(activityPanelSource, /待处理审批/);
  assert.match(activityPanelSource, /逐文件结果/);
  assert.match(activityPanelSource, /在编辑器中打开/);
  assert.match(activityPanelSource, /openArtifactInEditor/);
  assert.match(activityPanelSource, /explicit renderer user gesture/);
  assert.match(preloadSource, /onMcpOpenArtifact/);
  assert.match(mainLayoutSource, /handleMcpOpenArtifact/);
  assert.match(mainLayoutSource, /fileManagerStore\.addPathFiles/);
  assert.match(storeSource, /STATUS_PATTERN/);
  assert.match(storeSource, /ERROR_CODE_PATTERN/);
  assert.match(storeSource, /MCP_ACTIVITY_READ_FAILED/);
});
