export const SAM3_LEXICON_VERSION = 1;

export const DEFAULT_SAM3_COLOR_TERMS = Object.freeze([
  { zh: "红色", en: "red" },
  { zh: "蓝色", en: "blue" },
  { zh: "绿色", en: "green" },
  { zh: "黄色", en: "yellow" },
  { zh: "黑色", en: "black" },
  { zh: "白色", en: "white" },
  { zh: "灰色", en: "gray" },
  { zh: "橙色", en: "orange" },
  { zh: "紫色", en: "purple" },
  { zh: "粉色", en: "pink" },
  { zh: "棕色", en: "brown" },
  { zh: "金色", en: "gold" },
  { zh: "银色", en: "silver" },
  { zh: "浅红色", en: "light red" },
  { zh: "深红色", en: "dark red" },
  { zh: "浅蓝色", en: "light blue" },
  { zh: "深蓝色", en: "dark blue" },
  { zh: "浅绿色", en: "light green" },
  { zh: "深绿色", en: "dark green" },
  { zh: "透明", en: "transparent" },
]);

export const DEFAULT_SAM3_NOUN_TERMS = Object.freeze([
  { zh: "人", en: "person", category: "人物" },
  { zh: "男人", en: "man", category: "人物" },
  { zh: "女人", en: "woman", category: "人物" },
  { zh: "小孩", en: "child", category: "人物" },
  { zh: "儿童", en: "child", category: "人物" },
  { zh: "婴儿", en: "baby", category: "人物" },
  { zh: "脸", en: "face", category: "人物" },
  { zh: "头发", en: "hair", category: "人物" },
  { zh: "手", en: "hand", category: "人物" },
  { zh: "脚", en: "foot", category: "人物" },
  { zh: "鞋子", en: "shoe", category: "穿戴" },
  { zh: "上衣", en: "shirt", category: "穿戴" },
  { zh: "裤子", en: "pants", category: "穿戴" },
  { zh: "裙子", en: "dress", category: "穿戴" },
  { zh: "外套", en: "jacket", category: "穿戴" },
  { zh: "帽子", en: "hat", category: "穿戴" },
  { zh: "眼镜", en: "glasses", category: "穿戴" },
  { zh: "背包", en: "backpack", category: "穿戴" },
  { zh: "手提包", en: "handbag", category: "穿戴" },
  { zh: "手表", en: "watch", category: "穿戴" },
  { zh: "口罩", en: "face mask", category: "穿戴" },
  { zh: "猫", en: "cat", category: "动物" },
  { zh: "狗", en: "dog", category: "动物" },
  { zh: "鸟", en: "bird", category: "动物" },
  { zh: "鱼", en: "fish", category: "动物" },
  { zh: "马", en: "horse", category: "动物" },
  { zh: "牛", en: "cow", category: "动物" },
  { zh: "羊", en: "sheep", category: "动物" },
  { zh: "兔子", en: "rabbit", category: "动物" },
  { zh: "蝴蝶", en: "butterfly", category: "动物" },
  { zh: "昆虫", en: "insect", category: "动物" },
  { zh: "汽车", en: "car", category: "车辆" },
  { zh: "车辆", en: "vehicle", category: "车辆" },
  { zh: "卡车", en: "truck", category: "车辆" },
  { zh: "公交车", en: "bus", category: "车辆" },
  { zh: "自行车", en: "bicycle", category: "车辆" },
  { zh: "摩托车", en: "motorcycle", category: "车辆" },
  { zh: "火车", en: "train", category: "车辆" },
  { zh: "飞机", en: "airplane", category: "车辆" },
  { zh: "船", en: "boat", category: "车辆" },
  { zh: "轮胎", en: "tire", category: "车辆" },
  { zh: "车牌", en: "license plate", category: "车辆" },
  { zh: "房子", en: "house", category: "建筑" },
  { zh: "建筑", en: "building", category: "建筑" },
  { zh: "窗户", en: "window", category: "建筑" },
  { zh: "门", en: "door", category: "建筑" },
  { zh: "墙", en: "wall", category: "建筑" },
  { zh: "屋顶", en: "roof", category: "建筑" },
  { zh: "楼梯", en: "stairs", category: "建筑" },
  { zh: "栏杆", en: "railing", category: "建筑" },
  { zh: "道路", en: "road", category: "建筑" },
  { zh: "桥", en: "bridge", category: "建筑" },
  { zh: "树", en: "tree", category: "自然" },
  { zh: "花", en: "flower", category: "自然" },
  { zh: "草", en: "grass", category: "自然" },
  { zh: "草地", en: "grass", category: "自然" },
  { zh: "山", en: "mountain", category: "自然" },
  { zh: "石头", en: "rock", category: "自然" },
  { zh: "水", en: "water", category: "自然" },
  { zh: "水面", en: "water", category: "自然" },
  { zh: "天空", en: "sky", category: "自然" },
  { zh: "云", en: "cloud", category: "自然" },
  { zh: "太阳", en: "sun", category: "自然" },
  { zh: "月亮", en: "moon", category: "自然" },
  { zh: "桌子", en: "table", category: "生活物体" },
  { zh: "椅子", en: "chair", category: "生活物体" },
  { zh: "沙发", en: "sofa", category: "生活物体" },
  { zh: "床", en: "bed", category: "生活物体" },
  { zh: "柜子", en: "cabinet", category: "生活物体" },
  { zh: "杯子", en: "cup", category: "生活物体" },
  { zh: "瓶子", en: "bottle", category: "生活物体" },
  { zh: "碗", en: "bowl", category: "生活物体" },
  { zh: "盘子", en: "plate", category: "生活物体" },
  { zh: "手机", en: "phone", category: "电子设备" },
  { zh: "电脑", en: "computer", category: "电子设备" },
  { zh: "键盘", en: "keyboard", category: "电子设备" },
  { zh: "鼠标", en: "mouse", category: "电子设备" },
  { zh: "屏幕", en: "screen", category: "电子设备" },
  { zh: "书", en: "book", category: "生活物体" },
  { zh: "纸", en: "paper", category: "生活物体" },
  { zh: "盒子", en: "box", category: "生活物体" },
  { zh: "玩具", en: "toy", category: "生活物体" },
  { zh: "球", en: "ball", category: "生活物体" },
  { zh: "伞", en: "umbrella", category: "生活物体" },
  { zh: "苹果", en: "apple", category: "食物" },
  { zh: "香蕉", en: "banana", category: "食物" },
  { zh: "橙子", en: "orange fruit", category: "食物" },
  { zh: "面包", en: "bread", category: "食物" },
  { zh: "蛋糕", en: "cake", category: "食物" },
  { zh: "披萨", en: "pizza", category: "食物" },
  { zh: "米饭", en: "rice", category: "食物" },
  { zh: "肉", en: "meat", category: "食物" },
  { zh: "蔬菜", en: "vegetable", category: "食物" },
  { zh: "饮料", en: "drink", category: "食物" },
  { zh: "圆形", en: "circle", category: "形状" },
  { zh: "矩形", en: "rectangle", category: "形状" },
  { zh: "长方形", en: "rectangle", category: "形状" },
  { zh: "正方形", en: "square", category: "形状" },
  { zh: "方形", en: "square", category: "形状" },
  { zh: "三角形", en: "triangle", category: "形状" },
  { zh: "椭圆", en: "ellipse", category: "形状" },
  { zh: "文字", en: "text", category: "标识" },
  { zh: "数字", en: "number", category: "标识" },
  { zh: "标志", en: "sign", category: "标识" },
  { zh: "标识", en: "sign", category: "标识" },
  { zh: "图标", en: "icon", category: "标识" },
  { zh: "标签", en: "label", category: "标识" },
  { zh: "按钮", en: "button", category: "标识" },
  { zh: "箭头", en: "arrow", category: "标识" },
  { zh: "二维码", en: "QR code", category: "标识" },
  { zh: "条形码", en: "barcode", category: "标识" },
  { zh: "水印", en: "watermark", category: "标识" },
  { zh: "logo", en: "logo", category: "标识" },
]);

export const createDefaultSam3Lexicon = () => ({
  version: SAM3_LEXICON_VERSION,
  colors: DEFAULT_SAM3_COLOR_TERMS.map((item) => ({ ...item })),
  nouns: DEFAULT_SAM3_NOUN_TERMS.map((item) => ({ ...item })),
});
